-- Debug script to check if we can find columns for the table
USE ROLE accountadmin;
USE DATABASE CALL_CENTER;
USE SCHEMA TRANSCRIPTS;
use warehouse d4b_wh;

-- Test 1: Check if the table exists
SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_CATALOG = 'CALL_CENTER' 
AND TABLE_SCHEMA = 'TRANSCRIPTS' 
AND TABLE_NAME = 'CALL_TRANSCRIPTS';

-- Test 2: Check columns with exact case
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_CATALOG = 'CALL_CENTER' 
AND TABLE_SCHEMA = 'TRANSCRIPTS' 
AND TABLE_NAME = 'CALL_TRANSCRIPTS' 
ORDER BY ORDINAL_POSITION;

-- Test 3: Check columns with uppercase
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_CATALOG = 'CALL_CENTER' 
AND TABLE_SCHEMA = 'TRANSCRIPTS' 
AND TABLE_NAME = 'CALL_TRANSCRIPTS' 
ORDER BY ORDINAL_POSITION;

-- Test 4: Check what tables exist in that schema
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_CATALOG = 'CALL_CENTER' 
AND TABLE_SCHEMA = 'TRANSCRIPTS';
